security:
    erase_credentials: false

    encoders:
        AppBundle\Entity\Administrator: bcrypt
        AppBundle\Entity\Adherent: bcrypt
        legacy_encoder:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN_DASHBOARD: ~

        ROLE_ADMIN_MEDIAS:
            - ROLE_APP_ADMIN_MEDIA_ALL

        ROLE_ADMIN_CONTENT:
            - ROLE_APP_ADMIN_ARTICLE_ALL
            - ROLE_APP_ADMIN_PAGE_LIST
            - ROLE_APP_ADMIN_PAGE_EDIT
            - ROLE_APP_ADMIN_FACEBOOK_VIDEO_ALL
            - ROLE_APP_ADMIN_CLARIFICATION_ALL
            - ROLE_APP_ADMIN_SOCIAL_SHARE_CATEGORY_ALL
            - ROLE_APP_ADMIN_SOCIAL_SHARE_ALL
            - ROLE_APP_ADMIN_CUSTOM_SEARCH_RESULT_ALL

        ROLE_ADMIN_HOME:
            - ROLE_APP_ADMIN_HOME_BLOCK_EDIT
            - ROLE_APP_ADMIN_HOME_BLOCK_LIST
            - ROLE_APP_ADMIN_LIVE_LINK_ALL

        ROLE_ADMIN_PROPOSALS:
            - ROLE_APP_ADMIN_PROPOSAL_THEME_ALL
            - ROLE_APP_ADMIN_PROPOSAL_ALL

        ROLE_ADMIN_ORDERS:
            - ROLE_APP_ADMIN_ORDER_SECTION_ALL
            - ROLE_APP_ADMIN_ORDER_ARTICLE_ALL

        ROLE_ADMIN_FACEBOOK_PROFILES:
            - ROLE_APP_ADMIN_FACEBOOK_PROFILE_LIST
            - ROLE_APP_ADMIN_FACEBOOK_PROFILE_VIEW

        ROLE_ADMIN_REDIRECTIONS:
            - ROLE_APP_ADMIN_REDIRECTION_ALL

        ROLE_ADMIN_NEWSLETTER:
            - ROLE_APP_ADMIN_NEWSLETTER_SUBSCRIPTION_ALL
            - ROLE_APP_ADMIN_INVITE_EXPORT
            - ROLE_APP_ADMIN_INVITE_LIST
            - ROLE_APP_ADMIN_INVITE_VIEW
            - ROLE_APP_ADMIN_INVITE_DELETE

        ROLE_ADMIN_JE_MARCHE:
            - ROLE_APP_ADMIN_JE_MARCHE_EXPORT
            - ROLE_APP_ADMIN_JE_MARCHE_LIST
            - ROLE_APP_ADMIN_JE_MARCHE_VIEW
            - ROLE_APP_ADMIN_JE_MARCHE_DELETE

        ROLE_ADMIN_TON_MACRON:
            - ROLE_APP_ADMIN_TON_MACRON_CHOICE_LIST
            - ROLE_APP_ADMIN_TON_MACRON_CHOICE_CREATE
            - ROLE_APP_ADMIN_TON_MACRON_CHOICE_EDIT
            - ROLE_APP_ADMIN_TON_MACRON_CHOICE_DELETE
            - ROLE_APP_ADMIN_TON_MACRON_FRIEND_INVITATION_LIST
            - ROLE_APP_ADMIN_TON_MACRON_FRIEND_INVITATION_VIEW

        ROLE_ADMIN_LEGISLATIVES:
            - ROLE_APP_ADMIN_LEGISLATIVE_CANDIDATE_ALL
            - ROLE_APP_ADMIN_LEGISLATIVE_DISTRICT_ZONE_ALL

        ROLE_ADMIN_ADHERENTS:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_APP_ADMIN_ADHERENT_EXPORT
            - ROLE_APP_ADMIN_ADHERENT_LIST
            - ROLE_APP_ADMIN_ADHERENT_VIEW
            - ROLE_APP_ADMIN_ADHERENT_EDIT

        ROLE_ADMIN_UNREGISTRATIONS:
            - ROLE_APP_ADMIN_UNREGISTRATION_LIST
            - ROLE_APP_ADMIN_UNREGISTRATION_VIEW
            - ROLE_APP_ADMIN_UNREGISTRATION_EXPORT

        ROLE_ADMIN_SUMMARY:
            - ROLE_APP_ADMIN_SUMMARY_MISSION_TYPE_ALL
            - ROLE_APP_ADMIN_SUMMARY_LIST
            - ROLE_APP_ADMIN_SUMMARY_EXPORT

        ROLE_ADMIN_SKILLS:
            - ROLE_APP_ADMIN_SKILL_ALL

        ROLE_ADMIN_COMMITTEES:
            - ROLE_APP_ADMIN_COMMITTEE_EXPORT
            - ROLE_APP_ADMIN_COMMITTEE_LIST
            - ROLE_APP_ADMIN_COMMITTEE_VIEW
            - ROLE_APP_ADMIN_COMMITTEE_EDIT
            - ROLE_APP_ADMIN_COMMITTEE_DELETE

        ROLE_ADMIN_EVENTS:
            - ROLE_APP_ADMIN_EVENT_EXPORT
            - ROLE_APP_ADMIN_EVENT_LIST
            - ROLE_APP_ADMIN_EVENT_VIEW
            - ROLE_APP_ADMIN_EVENT_EDIT
            - ROLE_APP_ADMIN_EVENT_DELETE
            - ROLE_APP_ADMIN_EVENT_CATEGORY_ALL

        ROLE_ADMIN_CITIZEN_INITIATIVES:
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_EXPORT
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_LIST
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_VIEW
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_EDIT
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_DELETE
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_CATEGORY_ALL
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_ALL
            - ROLE_APP_ADMIN_CITIZEN_INITIATIVE_ASKING_HELP_ALL

        ROLE_ADMIN_PROCURATIONS:
            - ROLE_APP_ADMIN_PROCURATION_REQUEST_ALL
            - ROLE_APP_ADMIN_PROCURATION_PROXY_ALL

        ROLE_ADMIN_DONATIONS:
            - ROLE_APP_ADMIN_DONATION_EXPORT
            - ROLE_APP_ADMIN_DONATION_LIST
            - ROLE_APP_ADMIN_DONATION_VIEW

        ROLE_ADMIN_MAILJET:
            - ROLE_APP_ADMIN_MAILJET_EMAIL_EXPORT
            - ROLE_APP_ADMIN_MAILJET_EMAIL_LIST
            - ROLE_APP_ADMIN_MAILJET_EMAIL_VIEW

        ROLE_ADMIN_REFERENTS:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_APP_ADMIN_REFERENT_EXPORT
            - ROLE_APP_ADMIN_REFERENT_LIST
            - ROLE_APP_ADMIN_REFERENT_VIEW
            - ROLE_APP_ADMIN_REFERENT_EDIT
            - ROLE_APP_ADMIN_REFERENT_CREATE

        ROLE_ADMIN_REFERENTS_AREAS:
            - ROLE_APP_ADMIN_REFERENT_AREA_ALL

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN_DASHBOARD
            - ROLE_ADMIN_MEDIAS
            - ROLE_ADMIN_CONTENT
            - ROLE_ADMIN_HOME
            - ROLE_ADMIN_PROPOSALS
            - ROLE_ADMIN_ORDERS
            - ROLE_ADMIN_FACEBOOK_PROFILES
            - ROLE_ADMIN_REDIRECTIONS
            - ROLE_ADMIN_NEWSLETTER
            - ROLE_ADMIN_JE_MARCHE
            - ROLE_ADMIN_TON_MACRON
            - ROLE_ADMIN_LEGISLATIVES
            - ROLE_ADMIN_ADHERENTS
            - ROLE_ADMIN_UNREGISTRATIONS
            - ROLE_ADMIN_SUMMARY
            - ROLE_ADMIN_SKILLS
            - ROLE_ADMIN_COMMITTEES
            - ROLE_ADMIN_EVENTS
            - ROLE_ADMIN_CITIZEN_INITIATIVES
            - ROLE_ADMIN_PROCURATIONS
            - ROLE_ADMIN_DONATIONS
            - ROLE_ADMIN_MAILJET
            - ROLE_APP_ADMIN_PAGE_CREATE
            - ROLE_ADMIN_REFERENTS
            - ROLE_ADMIN_REFERENTS_AREAS

    access_decision_manager:
        strategy: unanimous

    providers:
        admins_db:
            entity: { class: 'AppBundle\Entity\Administrator' }
        users_db:
            entity: { class: 'AppBundle\Entity\Adherent' }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            context: main_context
            pattern: ^/admin
            provider: admins_db
            anonymous:
                secret: '%env(SECRET)%'
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login_check

                default_target_path: sonata_admin_dashboard
                always_use_default_target_path: true

                username_parameter: _admin_email
                password_parameter: _admin_password
                csrf_parameter: _admin_csrf
                csrf_token_id: authenticate_admin
            logout:
                path: app_admin_logout
                target: homepage

        main:
            context: main_context
            # No pattern means every path is behind this firewall
            provider: users_db
            switch_user:
                provider: users_db
            anonymous:
                secret: '%env(SECRET)%'
            form_login:
                login_path: app_adherent_login
                check_path: app_adherent_login_check

                default_target_path: app_search_events

                username_parameter: _adherent_email
                password_parameter: _adherent_password
                csrf_parameter: _adherent_csrf
                csrf_token_id: authenticate_adherent
            logout:
                path: app_adherent_logout
                target: homepage


    access_control:
        - { path: '^/espace-adherent/mon-compte', roles: [ROLE_ADHERENT] }
        - { path: '^/espace-adherent/mon-profil', roles: [ROLE_ADHERENT] }
        - { path: '^/espace-adherent/documents', roles: [ROLE_ADHERENT] }
        - { path: '^/espace-adherent/contacter', roles: [ROLE_ADHERENT] }
        - { path: '^/espace-adherent/mes-evenements', roles: [ROLE_ADHERENT] }
        - { path: '^/admin/login', roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: '^/admin/impersonation/exit', roles: [ROLE_PREVIOUS_ADMIN] }
        - { path: '^/admin', roles: [ROLE_ADMIN_DASHBOARD] }
        - { path: '^/membre/.*', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/initiative-citoyenne/*/*/abonner', roles: [ROLE_ADHERENT] }
